name: Simple Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: false
        type: string
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: tempo-dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg

      - name: Create Release
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          
          gh release create "$VERSION" \
            --title "Tempo $VERSION" \
            --notes "## What's New in Tempo $VERSION

          ### Downloads
          - **macOS Apple Silicon**: Download the \`.dmg\` file for M1/M2/M3 Mac computers

          ### Installation
          - **macOS**: Open the \`.dmg\` file and drag Tempo to Applications

          For more information, visit our [GitHub repository](https://github.com/FlorianBx/tempo)." \
            src-tauri/target/release/bundle/dmg/*.dmg
